scrcpy-git: auto updated to 3.3.3_r2875.gf3d4fde1-1
It has been built because:
* nvchecker detects the following updates: aur(0): 2.6.1_r2501.g44b3fd82-1 -> 3.3.3_r2875.gf3d4fde1-1

diff --git a/archoream/scrcpy-git/PKGBUILD b/archoream/scrcpy-git/PKGBUILD
--- a/archoream/scrcpy-git/PKGBUILD
+++ b/archoream/scrcpy-git/PKGBUILD
@@ -1,22 +1,21 @@
 # Merged with official ABS scrcpy PKGBUILD by João, 2023/05/14 (all respective contributors apply herein)
-# Maintainer: João Figueiredo & chaotic-aur <islandc0der@chaotic.cx>
+# Maintainer: Daniël Nazarkin <aur.danicatgames@pm.me>
+# Contributor: João Figueiredo & chaotic-aur <islandc0der@chaotic.cx>
 # Contributor: skydrome -at- protonmail
 
 pkgname=scrcpy-git
-pkgver=2.1.1_r2219.g90ca46ee
+pkgver=3.3.3_r2875.gf3d4fde1
 pkgrel=1
 pkgdesc='Display and control your Android device'
-arch=($CARCH)
+arch=('x86_64')
 url='https://github.com/Genymobile/scrcpy'
-license=(Apache)
-depends=(android-tools ffmpeg sdl2)
+license=(Apache-2.0)
+depends=(android-tools ffmpeg sdl2 glibc libusb hicolor-icon-theme)
 makedepends=(git meson)
 conflicts=(${pkgname%-git})
 provides=(${pkgname%-git})
-source=("git+https://github.com/Genymobile/${pkgname%-git}.git"
-        "$url/releases/download/v${pkgver%_*}/${pkgname%-git}-server-v${pkgver%_*}")
-sha256sums=('SKIP'
-            'SKIP')
+source=("git+https://github.com/Genymobile/${pkgname%-git}.git#branch=dev")
+sha256sums=('SKIP')
 
 pkgver() {
   cd ${pkgname%-git}
@@ -24,12 +23,27 @@ pkgver() {
   echo "${_ver}_r$(git rev-list --count HEAD).g$(git rev-parse --short HEAD)"
 }
 
+prepare() {
+  _url=$(grep '^PREBUILT_SERVER_URL=' "scrcpy/install_release.sh" | cut -d= -f2)
+  _sha256=$(grep '^PREBUILT_SERVER_SHA256=' "scrcpy/install_release.sh" | cut -d= -f2)
+  _file="${_url##*/}"
+
+  if [ ! -f "$_file" ]; then
+    curl -L -o "$_file" "$_url"
+  fi
+
+  echo "$_sha256 $_file" | sha256sum --check || {
+    echo "Error: server checksum failed"
+    exit 1
+  }
+}
+
 build() {
   mkdir -p build
   arch-meson build ${pkgname%-git} \
     -D b_lto=true \
     -D b_ndebug=true \
-    -D prebuilt_server=../${pkgname%-git}-server-v${pkgver%_*} \
+    -D prebuilt_server="../$_file" \
     --buildtype release
   ninja -C build
 }
